In [103]:
import keras
from keras.models import Sequential
from keras import optimizers
from keras.layers import Dense, Dropout,Activation, Flatten, Conv2D, MaxPooling2D, AveragePooling2D, GlobalMaxPooling2D, ZeroPadding2D, Input
from keras.models import Model
from keras.preprocessing import image
from sklearn.model_selection import train_test_split
import pandas as pd
import glob
import os
from PIL import Image
from tqdm import tqdm
import numpy as np
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
from keras.utils import to_categorical

In [ ]:
path = '/DataScienceClass/MINST_Digits_Identification/Images/train/'
train_images=[]
train_files=[]
for filename in glob.glob(path + '*.png'): #assuming gif 
    # the next line opens the image and convert it to grey scale
    im=Image.open(filename).convert('L')
    # the next line, Image.getdata returns the pixel values as sequence of flatten values
    data = im.getdata()
    nparray = np.array(data,'uint8')
    # print(nparray)
    train_images.append([nparray,os.path.basename(filename)])
#    train_files.append(os.path.basename(filename))
    im.close

In [28]:
path = 'C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/train_LbELtWX/train/'
train_images=[]
train_files=[]
for filename in glob.glob(path + '*.png'): #assuming gif 
    # the next line opens the image and convert it to grey scale
    #im=Image.open(filename).convert('L')
    # the next line, Image.getdata returns the pixel values as sequence of flatten values
    #data = im.getdata()
    #data = im.
    #nparray = np.array(data,'uint8')
    nparray = image.img_to_array(image.load_img(filename))
    #print(nparray.shape)
    train_images.append(nparray) #,os.path.basename(filename)])
#    train_files.append(os.path.basename(filename))
    im.close

In [ ]:
path = 'C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/train_LbELtWX/train/'
train_images=[]
train_files=[]
for filename in glob.glob(path + '*.png'):
    nparray = image.img_to_array(image.load_img(filename))
    train_images.append(nparray) 

In [35]:
path = 'C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/test_ScVgIM0/test/'
test_images=[]
test_files=[]
for filename in glob.glob(path + '*.png'):
    nparray = image.img_to_array(image.load_img(filename))
    test_images.append(nparray) 

In [25]:
len(train_images)

60000

In [36]:
np.array(test_images).shape

(10000, 28, 28, 3)

In [32]:
np.array(train_images).shape

(60000, 28, 28, 3)

In [38]:
len(train_images)

60000

In [ ]:
train = pd.read_csv

In [44]:
train_images[1].shape

(28, 28, 3)

In [49]:
np.array(train_images).shape[3]

3

In [52]:
np.array(train_images).shape

(60000, 28, 28, 3)

In [53]:
np.array(test_images).shape

(10000, 28, 28, 3)

In [54]:
np.array(train_images)

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

In [ ]:
train_image = []


In [55]:
X_train = np.array(train_images)

In [58]:
X_train.shape

(60000, 28, 28, 3)

In [59]:
train = pd.read_csv('C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/train_LbELtWX/train.csv')

In [60]:
test = pd.read_csv('C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/test_ScVgIM0/test.csv')

In [61]:
train.shape

(60000, 2)

In [62]:
train.head()

id  label
0   1      9
1   2      0
2   3      0
3   4      3
4   5      0

In [65]:
img = load_img('C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/train_LbELtWX/train/24280.png')
img

In [66]:
train[train.id==24280]

id  label
24279  24280      9

In [68]:
img = load_img('C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/train_LbELtWX/train/27454.png')
img

In [69]:
train[train.id==27454]

id  label
27453  27454      7

In [70]:
X = np.array(train_images)

In [71]:
X.shape

(60000, 28, 28, 3)

In [73]:
y = train['label'].values

In [74]:
y

array([9, 0, 0, ..., 3, 0, 5], dtype=int64)

In [77]:
y = to_categorical(y)

In [78]:
y

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [79]:
y.shape

(60000, 10)

In [83]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 42,test_size = 0.2)

In [84]:
X_train.shape

(48000, 28, 28, 3)

In [85]:
X_test.shape

(12000, 28, 28, 3)

In [86]:
y_train.shape

(48000, 10)

In [87]:
y_test.shape

(12000, 10)

In [95]:
model = Sequential()
model.add(Conv2D(32,kernel_size =(3,3),activation='relu',input_shape=(28,28,3)))
model.add(Conv2D(64,(3,3),activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))

In [96]:
model.compile(loss='categorical_crossentropy', optimizer = 'Adam',metrics=['accuracy'])

In [97]:
model.fit(X_train,y_train,epochs = 10,validation_data =(X_test, y_test))

Epoch 1/10
1500/1500 [==============================] - 59s 39ms/step - loss: 4.9754 - accuracy: 0.0980 - val_loss: 2.3029 - val_accuracy: 0.1001
Epoch 2/10
1500/1500 [==============================] - 61s 41ms/step - loss: 2.3038 - accuracy: 0.1013 - val_loss: 2.3027 - val_accuracy: 0.1002
Epoch 3/10
1500/1500 [==============================] - 61s 40ms/step - loss: 2.3028 - accuracy: 0.0967 - val_loss: 2.3027 - val_accuracy: 0.1002
Epoch 4/10
1500/1500 [==============================] - 61s 41ms/step - loss: 2.3030 - accuracy: 0.0967 - val_loss: 2.3027 - val_accuracy: 0.1002
Epoch 5/10
1500/1500 [==============================] - 61s 41ms/step - loss: 2.3030 - accuracy: 0.1016 - val_loss: 2.3026 - val_accuracy: 0.1002
Epoch 6/10
1500/1500 [==============================] - 62s 41ms/step - loss: 2.3054 - accuracy: 0.0983 - val_loss: 2.3027 - val_accuracy: 0.0987
Epoch 7/10
1500/1500 [==============================] - 63s 42ms/step - loss: 2.3026 - accuracy: 0.1033 - val_loss: 2.3026 -

In [98]:
model.compile(loss='categorical_crossentropy', optimizer = 'SGD',metrics=['accuracy'])

In [99]:
model.fit(X_train,y_train,epochs = 10,validation_data =(X_test, y_test))

Epoch 1/10
1500/1500 [==============================] - 58s 38ms/step - loss: 2.3027 - accuracy: 0.0984 - val_loss: 2.3027 - val_accuracy: 0.0966
Epoch 2/10
1500/1500 [==============================] - 60s 40ms/step - loss: 2.3026 - accuracy: 0.1004 - val_loss: 2.3026 - val_accuracy: 0.0966
Epoch 3/10
1500/1500 [==============================] - 60s 40ms/step - loss: 2.3027 - accuracy: 0.0993 - val_loss: 2.3027 - val_accuracy: 0.0966
Epoch 4/10
1500/1500 [==============================] - 60s 40ms/step - loss: 2.3027 - accuracy: 0.1009 - val_loss: 2.3027 - val_accuracy: 0.0966
Epoch 5/10
1500/1500 [==============================] - 62s 42ms/step - loss: 2.3027 - accuracy: 0.1001 - val_loss: 2.3027 - val_accuracy: 0.0997
Epoch 6/10
1500/1500 [==============================] - 61s 40ms/step - loss: 2.3027 - accuracy: 0.0964 - val_loss: 2.3026 - val_accuracy: 0.0966
Epoch 7/10
1500/1500 [==============================] - 61s 41ms/step - loss: 2.3027 - accuracy: 0.0983 - val_loss: 2.3027 -

In [104]:
train.shape[0]

60000

## Converting Train Image to GreyScale i.e Black and White Image

In [106]:
path = 'C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/train_LbELtWX/train/'
train_image=[]
train_file=[]
for i in tqdm(range(train.shape[0])): 
    img = image.load_img('C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/train_LbELtWX/train/'+train['id'][i].astype('str')+'.png', target_size=(28,28,1), grayscale=True)
    img = image.img_to_array(img)
    img = img/255
    train_image.append(img)
X1=np.array(train_image)

100%|██████████████████████████████████████████████████████████████████████████| 60000/60000 [00:20<00:00, 2929.57it/s]


In [107]:
np.array(train_image).shape

(60000, 28, 28, 1)

In [108]:
X1.shape

(60000, 28, 28, 1)

In [109]:
y1=train['label'].values
y1 = to_categorical(y1)

In [110]:
y1.shape

(60000, 10)

In [111]:
X1_train,X1_test,y1_train,y1_test = train_test_split(X1,y1,random_state=42,test_size = 0.2)

In [114]:
X1_train.shape

(48000, 28, 28, 1)

In [115]:
y1_train.shape

(48000, 10)

In [116]:
X1_test.shape

(12000, 28, 28, 1)

In [117]:
y1_test.shape

(12000, 10)

In [112]:
model_1 = Sequential()
model_1.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(28,28,1)))
model_1.add(Conv2D(64, (3, 3), activation='relu'))
model_1.add(MaxPooling2D(pool_size=(2, 2)))
model_1.add(Dropout(0.25))
model_1.add(Flatten())
model_1.add(Dense(128, activation='relu'))
model_1.add(Dropout(0.5))
model_1.add(Dense(10, activation='softmax'))

In [113]:
model_1.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [118]:
model_1.fit(X1_train, y1_train, epochs=10, validation_data=(X1_test, y1_test))

Epoch 1/10
1500/1500 [==============================] - 57s 37ms/step - loss: 0.6696 - accuracy: 0.7625 - val_loss: 0.3076 - val_accuracy: 0.8874
Epoch 2/10
1500/1500 [==============================] - 60s 40ms/step - loss: 0.3414 - accuracy: 0.8757 - val_loss: 0.2596 - val_accuracy: 0.9021
Epoch 3/10
1500/1500 [==============================] - 60s 40ms/step - loss: 0.2826 - accuracy: 0.8963 - val_loss: 0.2357 - val_accuracy: 0.9124
Epoch 4/10
1500/1500 [==============================] - 60s 40ms/step - loss: 0.2485 - accuracy: 0.9083 - val_loss: 0.2360 - val_accuracy: 0.9115
Epoch 5/10
1500/1500 [==============================] - 60s 40ms/step - loss: 0.2192 - accuracy: 0.9177 - val_loss: 0.2255 - val_accuracy: 0.9162
Epoch 6/10
1500/1500 [==============================] - 60s 40ms/step - loss: 0.2028 - accuracy: 0.9257 - val_loss: 0.2243 - val_accuracy: 0.9193
Epoch 7/10
1500/1500 [==============================] - 61s 41ms/step - loss: 0.1794 - accuracy: 0.9339 - val_loss: 0.2189 -

## Converting Test Images to GreyScale

In [119]:
test_image = []
for i in tqdm(range(test.shape[0])):
    img = image.load_img('C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/test_ScVgIM0/test/'+test['id'][i].astype('str')+'.png', target_size=(28,28,1), grayscale=True)
    img = image.img_to_array(img)
    img = img/255
    test_image.append(img)
test = np.array(test_image)

  0%|                                                                                        | 0/10000 [00:00<?, ?it/s]C:\Users\dell\anaconda3\lib\site-packages\keras_preprocessing\image\utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '
100%|██████████████████████████████████████████████████████████████████████████| 10000/10000 [00:05<00:00, 1741.37it/s]


In [121]:
# model_1 is a greyscale image and is of the shape(n,28,28,1), model is of shape (n,28,28,3) which is a rgb image
prediction = model_1.predict_classes(test)

In [122]:
sample = pd.read_csv('C:/Users/dell/Documents/AI-ML(Data Science Program)/Deep Learning for DataScience(started from 20-FEB-2021)/sample_submission_I5njJSF.csv')
sample['label'] = prediction
sample.to_csv('sample_cnn.csv', header=True, index=False)